INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2WOJ7D52Ng3myrKlEf4Azj', 'Big Body Benz', '148283', '74', '1', '4UmUrt9VYrAhLc9xnW13nf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4KfL3Ne8bc9bC2PUB8QGwA', 'Ich weiß nicht mal wie sie heißt', '168750', '73', '1', '1cfOfObZygQ6EyYveSyciJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5CqkgDH8QZjSqqI3HmYxDD', 'Airwaves', '178932', '84', '1', '4ZylcATH7a5JkgNNGXxwhJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7ytR5pFWmSjzHJIeQkgog4', 'ROCKSTAR (feat. Roddy Ricch)', '181733', '99', '7', '623PL2MBg50Br5dLXC9E9e');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3yZCjDTxzZxx1kll1sRjGc', 'Emotions 2.0', '146027', '78', '1', '3lAuhqYVnrNJjNjmspG1kt');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0rqY8g1Y1zaA4YwU6vhBQg', 'Boot', '193017', '81', '1', '0dGov1FjnwkB6tZ8gSGbP8');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1xQ6trAsedVPCdbtDAmk0c', 'Savage Love (Laxed - Siren Beat)', '171374', '83', '1', '1XMw3pBrYeXzNXZXc84DNw');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3goH7O78TLkV9RhCAyM4AT', 'Fame', '173760', '84', '1', '5ANcyb7GrRVY6LZDZKZ72C');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6BXyD6UUPizpRpA7iOi99r', 'In meinem Benz', '164203', '81', '1', '5tbHIthcp7hMP4dkDabPEx');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1EbdQ54jFLGEH94cUif3TI', '7 Stunden', '174680', '79', '10', '1L2yFZquYx9fjAPYWGWwZQ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0VjIjW4GlUZAMYd2vXMi3b', 'Blinding Lights', '200040', '100', '9', '4yP0hdKOZPNshxUOjY0cZj');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5TGcyccg8Hkgn9jB7gUpMN', 'Never Let Me Down', '153148', '53', '1', '6uuyNkiv7V6IbOZPmEPtsL');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0BwO44CBPFWxAIO5ZbPf3N', 'Roadrunner', '149028', '82', '1', '4cuugnRQi0d3f8c2Fv3vJI');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('17tgK6f93CECWj0EC70RfQ', 'Shakira', '184000', '67', '1', '5ojit3NQ6vpRRu8bp9gbEI');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6bRR9tU3WUBsC4aywSgHEO', 'WEISSER RAUCH', '182924', '64', '4', '2LMgEQmQ2JRhNmXMvXEjCN');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5t3PF7pHuiwwLbNCJ8mn4N', 'MedMen', '161120', '66', '1', '26rdmChDovaGc0y2vzSci6');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('24Yi9hE78yPEbZ4kxyoXAI', 'Roses - Imanbek Remix', '176840', '97', '1', '3GqSdhWjmMypMwPLtzoFYs');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1WoM4mof0Nl1xPtwf6h6ow', 'FLY', '174893', '80', '1', '4Ve9yWpcqa5lmjcp7UKK7h');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2rxxXYtTIFKyrhJpofeoIX', 'valla nein! (feat. Luciano)', '182040', '79', '1', '2Qhq1PHID06iBhMUzryH8Z');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6lU4BQWZomCWRfKSowfezE', 'Emotions', '146012', '82', '8', '4UUOJrs6MUmkshzvSbKpAg');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('76nqCfJOcFFWBJN32PAksn', 'Kings & Queens', '162398', '89', '1', '6yUkGEJftbJl1QPvz4WTjO');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('62aP9fBQKYKxi7PDXwcUAS', 'ily (i love you baby) (feat. Emilee)', '176546', '95', '1', '4MHHajvRTUHItDsvfdIC8B');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3H7ihDc1dqLriiWXwsc2po', 'Breaking Me', '166793', '93', '1', '3nBQlhUvErkw8DVpF47WAn');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2aVza5KlpqG1LXcdBNn6R3', 'Sonne', '164360', '67', '1', '7tPelVBAMqSqL8T4a8osq9');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('24IgCW19L8lXKyFZwzFtD3', 'MAMACITA', '251428', '36', '3', '2eORe6u9TPXYisYshyXVeH');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0KONCbkFfQlOj7SFo4pnFb', 'Dopeboy', '166536', '65', '1', '1wF1W4HGhn4xhIzzeQBP3p');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3qT2eKpWNq5cze7kGGORDZ', 'DAS RENNEN', '193684', '77', '1', '38xCCfybcmBDFD1HVyHhSy');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1NP7bzm8UksJUWXsuFoOwE', 'Übermorgen', '163275', '75', '1', '3Xhe03YALEzdpDqnKbgXvo');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6RYPJUBsL3w0k1CHKYtrRF', 'SoSo (feat. Dardan)', '163000', '64', '3', '7JduRA9DQiGqxM3Wh22rLl');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6hw1Sy9wZ8UCxYGdpKrU6M', 'Roller', '157093', '77', '2', '0IoleYbJxOgQLuZDkzyzPG');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('466cKvZn1j45IpxDdYZqdA', 'Toosie Slide', '247058', '87', '5', '6OQ9gBfg5EXeNAEwGSs6jK');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3037SYUA7xO7LGLQbl1DjA', 'Snowbunny', '134893', '64', '1', '5O4zMWF6cW9bg4QHAN0NRE');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7C1trmcQQ5n5RNy4l6ziCv', 'Some Say - Felix Jaehn Remix', '186878', '85', '1', '3HE3e3QqmuhAsxcJGtxyEr');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('58slk34NrSRuQvCxwrpweS', 'Kaioken (feat. Tory Lanez)', '169946', '62', '1', '0fBXOifdpHkGjRRBPst0bR');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6NTQ5VjDw2q130890wDWL0', 'Déjàvus im Kopf', '222715', '64', '1', '259RTiUVKhMhzTm3m6cTCN');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5UDK6yzqiW4kJU3YQauYR5', 'SANDMANN', '165194', '76', '1', '4lFgJJVND3DYX13YEtJNPR');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3dVvWnj4D8JGkKvo6Hucso', 'TROLLZ (with Nicki Minaj)', '202666', '86', '1', '7k3BOYZVMerwnrGSTBPJwD');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5B9CtjeguIO9LeOk8Xs1J3', 'Ich würd_ lügen', '163000', '33', '5', '33u8HE5uS7gMHTXmHYaFRc');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4NhDYoQTYCdWHTvlbGVgwo', 'GOOBA', '132303', '94', '1', '4kIWi5LcrqAWQD09CE05Ps');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1rgnBhdG2JDFTbYkYRZAku', 'Dance Monkey', '209754', '72', '1', '31IDBea3eEs57a0joX6TjN');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('50Td3qilgs8BLtv8mHyT1t', 'Control', '230880', '81', '1', '4w177LbRYa3z07NifGptFp');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0U9dP3BUlAgq9KkJXOijBH', 'SKRR', '119039', '78', '1', '6foqfeHIP2zkV5dCOckumg');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4nK5YrxbMGZstTLbvj6Gxw', 'Supalonely', '223480', '95', '2', '3ZJSoxsPMkNC9eb6gUn0Q8');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('525GY0mXYnxajolwgS8Eaz', 'Cooler Than Me', '179760', '78', '1', '5BmY6ZPLmhyIm9bRdN4mWP');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7My1iCGUznwNztIokee32S', 'Take My Hand', '162666', '31', '1', '4ihvYV9pDx9igLvotVKB9Q');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7ju97lgwC2rKQ6wwsf9no9', 'Rain On Me (with Ariana Grande)', '182200', '88', '4', '05c49JgPmL4Uz2ZeqRx5SP');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7hr6WRm7HUlVdkfnhSTm0G', 'Like I Love You', '203560', '68', '4', '51LrCn7WwuMfGwQufI1Esl');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7v8OynJxOxHoeS5C2UA9Y7', 'Nicht verdient', '176952', '80', '1', '0x7agz9XATuBItHpQyeD83');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2u6Jm2klS4yvAlbSHlxUwI', 'Alane', '175016', '66', '1', '537cgkkJUqMb46JUSNh0n7');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('61ZM92T2zaXIVsqncThQzC', 'In Your Eyes (feat. Alida)', '208222', '86', '1', '7Aq8cN8Br8AHcDqC327dlV');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0KBwGCY9RYD9t2zjeW4h48', 'Djomb - Bien ou quoi', '141893', '81', '16', '70FpaoDALiemmQYyx3X1z7');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7b0ZEfaKg3OctqL115hUAg', 'Allez nique ta mère', '163273', '73', '1', '7HK0OTtfITzC6uSsGgyJoe');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6ab3CQvDlAVttThZucwGQ1', 'Angela', '236000', '80', '14', '07bBgskS3ghKJIWvwsgnqF');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('11Mq1tJwmFOig3BXxjqcQr', 'Italia', '212840', '67', '2', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('62Pp6exz0ywSlBqvNqiY6Z', 'Anissa', '175752', '76', '1', '5xPYfWKHgxj7jARUJza5eM');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1fyVvRQsa095P7QK5Um7xH', 'Grand bain', '207076', '36', '1', '7vll2UdYabMRy58Md168VB');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3zbZNJ1yewL5HqjvIEjjUD', 'Folie', '238200', '58', '1', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4fW3EMRzAfj8aNMsF3zMwt', 'JAUNÉ', '215947', '78', '1', '05DYj9x3CIoQg3EKQAI4Se');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4zfih9sHVVJMb0f7LRoAz8', 'Sousou', '237586', '54', '1', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2alc8VZAzDgdAsL2QMk3hu', 'Skechers', '106000', '89', '1', '4a50hfH6HJQywmghPYnRRW');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5HEtuK03ygUzqca6yfgOYZ', 'Lettre à une femme', '157766', '76', '12', '7MYn9BLGDun0DFxKKQUrWJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('07pzk5h8p2qRowPZb3YBKC', '10K', '176973', '73', '11', '3jIRYmaxJfp854j8QtfVNI');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6UzGRgt50CWkj2ELI4twvX', 'MACINTOSH', '145586', '61', '1', '1boYX0lfrhR57mdEfl0LEn');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3lTL4LdFKVF51lseI2nk5D', '6.3', '212320', '69', '10', '2tqPdi5mS2Ol41V81256zd');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1jNx8kPZZDu5RMNXS7AKMS', 'Ça sent bon', '224893', '63', '3', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0BD9boQC7jUTWkAoib4Z0d', 'Meleğim', '220280', '70', '6', '6tGI9MGbLjbxyzcxYkMXPJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7k4t7uLgtOxPwTpFmtJNTY', 'Tusa', '200960', '92', '1', '7mKevNHhVnZER3BLgI8O4F');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5GyyPRvEwdI4wJSUbzxHQv', 'Blanche', '193453', '76', '5', '5jzZ6P5fwaHQ3RWCaxN3IP');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1sVhgnJn5xmT2aC4l2Vxyp', 'Veste Quechua', '175973', '61', '11', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4mtY2gjqFFWTMnzaQPvERm', 'Bro Bro', '144346', '74', '1', '7I6GbayAYZCTs1T2Zpa31l');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('69I4Eynuxdj6LEmpvG56u6', 'Crois-moi (feat. Ninho)', '183560', '74', '4', '0QOCs2S4yp3M47sNZGCUqY');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('54BjygUE4flw6z7MEITRW7', 'Coeur Noir', '137080', '66', '8', '70FpaoDALiemmQYyx3X1z7');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5A5MuLA4J7V8MZ2UoexDtb', 'Que ça dure', '307120', '61', '5', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1Sb7QJRawbARgpMqyYNMkT', 'Distant', '162013', '72', '8', '5jzZ6P5fwaHQ3RWCaxN3IP');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5wEg5O6wWFQGB60NmLeOlv', 'Aucune limite', '186847', '65', '1', '1a9SoMIPKjXid1oaB6V8Vi');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4Nfak8iMF4kQfQ6Pa8Z79m', 'Dybala', '211226', '74', '11', '5jzZ6P5fwaHQ3RWCaxN3IP');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7eJMfftS33KTjuF7lTsMCx', 'death bed (coffee for your head) (feat. beabadoobee)', '173333', '97', '1', '2p9gK2BcdrloHNJwarc9gc');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('72j6CMlN5NCzF0oLMyfFcQ', 'Pour la street', '192013', '61', '4', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2LmA2W8q5tf9FKq1EGdB2W', 'Toi-même tu sais', '233146', '60', '8', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1qzyOOQjLFYhWQ7AIbU67t', 'Rentrez pas dans ma tête', '250973', '61', '5', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4prFpE31NrviWFOEcwNGSD', 'Bravo', '285013', '60', '10', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1Lulg5ZiMEXy3QNwb1PB8I', 'Zipette', '211262', '73', '3', '7MYn9BLGDun0DFxKKQUrWJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7szuecWAPwGoV1e5vGu8tl', 'In Your Eyes', '237520', '91', '10', '4yP0hdKOZPNshxUOjY0cZj');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2VXeQ7moo4zfT6EFO3Cwse', 'Train de vie (feat. PLK)', '187146', '73', '2', '7zMKpKCOSDLZ0BTX5XwbV0');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('67ya7abHhAXsYGg4yg59UU', 'Eh ouais fils', '184493', '61', '6', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0ucEyG8AH7212ESdvVjMci', 'Je suis pas ton pote', '205453', '60', '9', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0Nexr4ce2q2LIrrqCQkuWh', 'Fait d_or', '314760', '56', '15', '5e5kGSnnDPARPjjrUdGWjf');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5kQ5tKaEs3RHlaLqwjagly', 'So Maness', '159400', '63', '11', '5VV5rWG1RI5KpfXBS3emRQ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7HnZCmNXgva6N3kZiK0NTn', 'MD (feat. Niska)', '210826', '69', '6', '6K1OEOn1CQxPJJYKIeJaPo');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4TnFANpjVwVKWzkxNzIyFH', 'Ne reviens pas', '188613', '71', '7', '7ilqGyawRNe3bXNfLYtrfo');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0Jh6iWjna1wk5le0Ahn7No', 'La vie qu_on mène', '193443', '74', '2', '14p5CVdJCMRcgvICDAGS7k');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6UelLqGlWMcVH1E5c4H7lY', 'Watermelon Sugar', '174000', '92', '2', '7xV2TzoaVc0ycW7fwBwAml');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3PfIrDoz19wz7qK7tYeu62', 'Don_t Start Now', '183290', '89', '2', '7fJJK56U9fHixgO0HQkhtI');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5RqR4ZCCKJDcBLIn4sih9l', 'Party Girl', '147800', '94', '1', '4NPX54YtocHqTOq6yXDEFM');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('017PF4Q3l4DBUiWoXk4OWT', 'Break My Heart', '221820', '90', '9', '7fJJK56U9fHixgO0HQkhtI');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('22LAwLoDA5b4AaGSkg6bKW', 'Blueberry Faygo', '162546', '88', '1', '2a1AHCq835BXUcX1aTTWqQ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0nbXyq5TXYPCO7pr3N8S4I', 'The Box', '196652', '95', '2', '52u4anZbHd6UInnmHRFzba');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4HBZA5flZLE435QTztThqH', 'Stuck with U (with Justin Bieber)', '228482', '94', '1', '5mUdh6YWnUvf0MfklEk1oi');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('39Yp9wwQiSRIDOvrVg7mbk', 'THE SCOTTS', '165977', '95', '1', '7q6zjWaLw8bN5nYiBWjrus');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4umIPjkehX1r7uhmGvXiSV', 'Intentions (feat. Quavo)', '212866', '88', '4', '63iWSELt9V1kV6RSMxN7Ii');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7qEHsqek33rTcFNT9PFqLf', 'Someone You Loved', '182160', '92', '4', '5658aM19fA3JVwTK6eQX70');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1Cv1YLb4q0RzL6pybtaMLo', 'Sunday Best', '158571', '93', '7', '3mMWlBGocBwsS1Q0o9wvlc');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2rRJrJEo19S2J82BDsQ3F7', 'Falling', '159381', '83', '10', '1Hy76RlNvOHe6cpih1RxXq');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5v4GgrXPMghOnBBLmveLac', 'Savage Remix (feat. Beyoncé)', '242000', '92', '1', '6M4VOF1ExBRii1x20Pk0GR');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1mohfLaTJtB2RplHLQVM70', 'La Jeepeta - Remix', '345240', '88', '1', '5emzM1P5GGeroiivNQgCq4');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3Dv1eDb0MEgF93GpLXlucZ', 'Say So', '237893', '93', '5', '1MmVkhiwTH0BkNOU3nw5d3');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('21jGcNKet2qwijlDFuPiPb', 'Circles', '215280', '93', '6', '4g1ZRSobMefqF6nelkgibi');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3ZG8N7aWw2meb6UrI5ZmnZ', 'Relación', '184254', '79', '9', '3D1NZYi3GsenO5uWDFrRI6');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2gMXnyrvIjhVBUZwvLZDMP', 'Before You Go', '215106', '84', '13', '2wiPF3m0ylst0JSk1IvZL8');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0SqqAgdovOE24BzxIClpjw', 'Yo Perreo Sola', '172127', '92', '5', '5lJqux7orBlA1QzyiBGti1');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6gBFPUFcJLzWGx4lenP6h2', 'goosebumps', '243836', '92', '9', '42WVQWuf1teDysXiOupIZt');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4DpNNXFMMxQEKl7r0ykkWA', 'Play Date', '179867', '91', '14', '5JpH5T1sCYnUyZD6TM0QaY');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1jaTQ3nqY3oAAYyCTbIvnM', 'WHATS POPPIN', '139741', '92', '1', '7AaqMMiYMvnMB3RcS8u3EY');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('06s3QtMJVXw1AJX3UfvZG1', 'Hasta Que Dios Diga', '246000', '89', '5', '7JtT7OyWM8BnIS5FXXPMKg');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2DEZmgHKAvm41k4J3R2E9Y', 'Safaera', '295176', '92', '14', '5lJqux7orBlA1QzyiBGti1');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1sgDyuLooyvEML4oHspNza', 'Lose Somebody', '199549', '79', '2', '7tcs1X9pzFvcLOPuhCstQJ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3jjujdWJ72nww5eGnfs2E7', 'Adore You', '207133', '88', '3', '7xV2TzoaVc0ycW7fwBwAml');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4w47S36wQGBhGg073q3nt7', 'TKN (feat. Travis Scott)', '129370', '90', '1', '4KEOAWBMpvJrIZ7tQfx44i');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3Z8FwOEN59mRMxDCtb8N0A', 'Be Kind (with Halsey)', '172761', '91', '1', '1eleCBhP2R8TXEDquvybwC');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2b8fOow8UzyDFAE27YhOZM', 'Memories', '189486', '91', '1', '3nR9B40hYLKLcR0Eph3Goc');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6v3KW9xbzN5yKLt9YKDYA2', 'Señorita', '190799', '83', '1', '0xzScN8P3hQAz3BT3YYX5w');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3eekarcy7kvN4yt5ZFzltW', 'HIGHEST IN THE ROOM', '175720', '91', '1', '2uDTi1PlpSpvAv7IRAoAEU');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('696DnlkuDOXcMAnKlTgXXK', 'ROXANNE', '163636', '92', '1', '6HJDrXs0hpebaRFKA1sF90');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1K5KBOgreBi5fkEHvg5ap3', 'Life Is Good (feat. Drake)', '237918', '79', '17', '4bNPOFOzxGhF5jhfIK6lit');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6q2uIyLqASSpv2SIv2ehWK', 'VACATION', '192935', '68', '1', '42XA3CG4dOtlaVKq5ZRNRh');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('44gRhRi2OhEf7moAUj6MD1', 'The Bigger Picture', '252728', '83', '1', '6ZTl8hHvYNuEg4Mk8yxz75');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5QZKcQDp0tCcvMdyqEciBV', 'Tommy Lee (feat. Post Malone)', '224638', '83', '1', '2PFiZ23ZyPTcgwmXk4X6o0');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('527k23H0A4Q0UJN3vGs0Da', 'After Party', '167915', '90', '4', '7z4GhRfLqfSkqrj5F3Yt2B');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4cSSL3YafYjM3yjgFO1vJg', 'Walk Em Down (feat. Roddy Ricch)', '173288', '89', '1', '3EYg0XBIcyz3OvhIy7gsZQ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2t7D3y0jvYjR8IP9Bosyew', 'GO (feat. Juice WRLD)', '183947', '82', '1', '40wtKuLVVlde1T88LqtZwa');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0RiRZpuVRbi7oqRdSMwhQY', 'Sunflower - Spider-Man: Into the Spider-Verse', '157560', '83', '12', '4g1ZRSobMefqF6nelkgibi');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('4wVOKKEHUJxHCFFNUWDn0B', 'Chicago Freestyle (feat. Giveon)', '220487', '89', '3', '6OQ9gBfg5EXeNAEwGSs6jK');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2qzUpSVI4NnPyWxbXwumTj', 'BLACK PARADE', '281272', '68', '1', '3MJxH055n52Rbm8RLlpJcN');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('6gxKUmycQX7uyMwJcweFjp', 'We Paid (feat. 42 Dugg)', '181929', '80', '26', '6uhEg4ASZYLIilZFCBFy1r');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2QqJTIlGKRLJC3onkavYEz', 'Flex (feat. Juice WRLD)', '163902', '86', '4', '39xhYyNNDatQtgKw2KdXMz');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('0OyQns5ayNK2OVaES0Vb8t', 'Righteous', '243356', '89', '1', '5hxLDyEJV1IvgoAquaImWW');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('285pBltuF7vW8TeWk8hdRR', 'Lucid Dreams', '239835', '89', '3', '6tkjU4Umpo79wwkgPMV3nZ');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3nS9a01VvXHQriLqJYwRqG', 'DOLLAZ ON MY HEAD (feat. Young Thug)', '197760', '85', '5', '0gA0nZrZ55PLUp7ARfrICu');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('7aiClxsDWFRQ0Kzk5KI5ku', 'hot girl bummer', '185093', '88', '1', '37CqAwxTungNxKpIK5vSgE');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('3QzAOrNlsabgbMwlZt7TAY', 'Ballin_ (with Roddy Ricch)', '180434', '87', '9', '2WrNHOba5u6P9S9xEboaUy');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('2AlYncTpVHKwHb55F9lF6O', 'Deep End Freestyle', '115200', '67', '1', '3P7EIeXmzJQNT1xs4Q6Xzd');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('07KXEDMj78x68D884wgVEm', 'High Fashion (feat. Mustard)', '220486', '87', '11', '52u4anZbHd6UInnmHRFzba');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('5MwynWK9s4hlyKHqhkNn4A', 'Chasin_ You', '205453', '81', '9', '1IR2nlwX6YVTXXeu2qzoWO');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1oOEkBNp4zWnkD7nWjJdog', 'Snow On Tha Bluff', '235480', '79', '1', '0MXpE6m0mEK0r3TuERb9Yd');
INSERT INTO track ('track_id', 'name', 'duration', 'popularity', 'track_number', 'album_id') VALUES ('1orjH4IkSH9VrWmRCToKV8', 'Shotta Flow 5', '145167', '79', '1', '1wEEKxybMlEo2Hob9oQA2y');
