INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4UmUrt9VYrAhLc9xnW13nf', 'Big Body Benz', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1cfOfObZygQ6EyYveSyciJ', 'Ich weiß nicht mal wie sie heißt', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4ZylcATH7a5JkgNNGXxwhJ', 'Airwaves', '2020-05-14', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('623PL2MBg50Br5dLXC9E9e', 'BLAME IT ON BABY', '2020-04-17', '13');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3lAuhqYVnrNJjNjmspG1kt', 'Emotions 2.0', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0dGov1FjnwkB6tZ8gSGbP8', 'Boot', '2020-06-05', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1XMw3pBrYeXzNXZXc84DNw', 'Savage Love (Laxed - Siren Beat)', '2020-06-11', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5ANcyb7GrRVY6LZDZKZ72C', 'Fame', '2020-05-08', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5tbHIthcp7hMP4dkDabPEx', 'In meinem Benz', '2020-05-29', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1L2yFZquYx9fjAPYWGWwZQ', 'Treppenhaus', '2020-05-29', '13');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4yP0hdKOZPNshxUOjY0cZj', 'After Hours', '2020-03-20', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6uuyNkiv7V6IbOZPmEPtsL', 'Never Let Me Down', '2020-04-24', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4cuugnRQi0d3f8c2Fv3vJI', 'Roadrunner', '2020-05-21', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5ojit3NQ6vpRRu8bp9gbEI', 'Shakira', '2020-06-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2LMgEQmQ2JRhNmXMvXEjCN', 'LONDON DRY', '2020-06-04', '8');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('26rdmChDovaGc0y2vzSci6', 'MedMen', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3GqSdhWjmMypMwPLtzoFYs', 'Roses (Imanbek Remix)', '2019-10-09', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4Ve9yWpcqa5lmjcp7UKK7h', 'FLY', '2020-05-29', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2Qhq1PHID06iBhMUzryH8Z', 'valla nein! (feat. Luciano)', '2020-06-05', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4UUOJrs6MUmkshzvSbKpAg', 'Rich Rich', '2020-04-24', '13');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6yUkGEJftbJl1QPvz4WTjO', 'Kings & Queens', '2020-03-12', '2');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4MHHajvRTUHItDsvfdIC8B', 'ily (i love you baby) (feat. Emilee)', '2019-11-26', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3nBQlhUvErkw8DVpF47WAn', 'Breaking Me', '2019-12-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7tPelVBAMqSqL8T4a8osq9', 'Sonne', '2020-06-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2eORe6u9TPXYisYshyXVeH', 'Translation', '2020-06-18', '15');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1wF1W4HGhn4xhIzzeQBP3p', 'Dopeboy', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('38xCCfybcmBDFD1HVyHhSy', 'DAS RENNEN', '2020-06-05', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3Xhe03YALEzdpDqnKbgXvo', 'Übermorgen', '2020-05-01', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7JduRA9DQiGqxM3Wh22rLl', 'Medical Heartbreak', '2020-06-19', '8');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0IoleYbJxOgQLuZDkzyzPG', 'Platte', '2019-10-25', '8');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6OQ9gBfg5EXeNAEwGSs6jK', 'Dark Lane Demo Tapes', '2020-05-01', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5O4zMWF6cW9bg4QHAN0NRE', 'Snowbunny', '2020-06-18', '4');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3HE3e3QqmuhAsxcJGtxyEr', 'Some Say (Felix Jaehn Remix)', '2020-01-10', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0fBXOifdpHkGjRRBPst0bR', 'Super Genkidama', '2020-06-19', '19');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('259RTiUVKhMhzTm3m6cTCN', 'Déjàvus im Kopf', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4lFgJJVND3DYX13YEtJNPR', 'SANDMANN', '2020-05-29', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7k3BOYZVMerwnrGSTBPJwD', 'TROLLZ (with Nicki Minaj)', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('33u8HE5uS7gMHTXmHYaFRc', 'Struggle Is Real', '2020-04-03', '11');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4kIWi5LcrqAWQD09CE05Ps', 'GOOBA', '2020-05-08', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('31IDBea3eEs57a0joX6TjN', 'Dance Monkey', '2019-05-10', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4w177LbRYa3z07NifGptFp', 'Control', '2020-03-13', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6foqfeHIP2zkV5dCOckumg', 'SKRR', '2020-04-23', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3ZJSoxsPMkNC9eb6gUn0Q8', 'STELLA & STEVE', '2019-11-15', '5');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5BmY6ZPLmhyIm9bRdN4mWP', 'Cooler Than Me', '2019-05-17', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4ihvYV9pDx9igLvotVKB9Q', 'Take My Hand', '2020-02-21', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('05c49JgPmL4Uz2ZeqRx5SP', 'Chromatica', '2020-05-29', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('51LrCn7WwuMfGwQufI1Esl', 'Nico Santos', '2020-05-08', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0x7agz9XATuBItHpQyeD83', 'Nicht verdient', '2020-04-29', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('537cgkkJUqMb46JUSNh0n7', 'Alane', '2020-06-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7Aq8cN8Br8AHcDqC327dlV', 'In Your Eyes (feat. Alida)', '2020-01-10', '3');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('70FpaoDALiemmQYyx3X1z7', 'Synkinisi', '2020-05-29', '20');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7HK0OTtfITzC6uSsGgyJoe', 'Allez nique ta mère', '2020-06-11', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('07bBgskS3ghKJIWvwsgnqF', 'Chaise pliante', '2019-08-30', '17');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5e5kGSnnDPARPjjrUdGWjf', 'La machine', '2020-06-19', '30');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5xPYfWKHgxj7jARUJza5eM', 'Anissa', '2020-04-15', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7vll2UdYabMRy58Md168VB', 'Poison Ou Antidote', '2019-12-20', '30');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('05DYj9x3CIoQg3EKQAI4Se', 'JAUNÉ', '2020-05-11', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4a50hfH6HJQywmghPYnRRW', 'Skechers', '2020-01-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7MYn9BLGDun0DFxKKQUrWJ', 'M.I.L.S 3', '2020-03-07', '17');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3jIRYmaxJfp854j8QtfVNI', 'Vol 169', '2020-05-28', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1boYX0lfrhR57mdEfl0LEn', 'MACINTOSH', '2020-06-18', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2tqPdi5mS2Ol41V81256zd', 'Carré VIP', '2020-02-28', '22');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6tGI9MGbLjbxyzcxYkMXPJ', 'Vintage', '2020-03-19', '20');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7mKevNHhVnZER3BLgI8O4F', 'Tusa', '2019-11-07', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5jzZ6P5fwaHQ3RWCaxN3IP', 'Les derniers salopards', '2020-01-16', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7I6GbayAYZCTs1T2Zpa31l', 'Bro Bro', '2020-05-08', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0QOCs2S4yp3M47sNZGCUqY', 'Architecte', '2020-04-03', '19');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1a9SoMIPKjXid1oaB6V8Vi', 'Aucune limite', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2p9gK2BcdrloHNJwarc9gc', 'death bed (coffee for your head) (feat. beabadoobee)', '2020-02-08', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7zMKpKCOSDLZ0BTX5XwbV0', 'Virus: avant l_album', '2020-04-17', '5');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5VV5rWG1RI5KpfXBS3emRQ', 'Mistral', '2020-06-05', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6K1OEOn1CQxPJJYKIeJaPo', 'Vie d_artiste', '2020-01-03', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7ilqGyawRNe3bXNfLYtrfo', 'Zone 59', '2019-11-29', '21');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('14p5CVdJCMRcgvICDAGS7k', 'Destin', '2019-03-22', '18');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7xV2TzoaVc0ycW7fwBwAml', 'Fine Line', '2019-12-13', '12');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7fJJK56U9fHixgO0HQkhtI', 'Future Nostalgia', '2020-03-27', '11');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4NPX54YtocHqTOq6yXDEFM', 'Party Girl', '2020-04-21', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2a1AHCq835BXUcX1aTTWqQ', 'Certified Hitmaker', '2020-02-06', '15');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('52u4anZbHd6UInnmHRFzba', 'Please Excuse Me For Being Antisocial', '2019-12-06', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5mUdh6YWnUvf0MfklEk1oi', 'Stuck with U', '2020-05-08', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7q6zjWaLw8bN5nYiBWjrus', 'THE SCOTTS', '2020-04-24', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('63iWSELt9V1kV6RSMxN7Ii', 'Changes', '2020-02-14', '17');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5658aM19fA3JVwTK6eQX70', 'Divinely Uninspired To A Hellish Extent', '2019-05-17', '12');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3mMWlBGocBwsS1Q0o9wvlc', 'Where the Light Is', '2019-01-06', '10');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1Hy76RlNvOHe6cpih1RxXq', 'Nicotine', '2020-03-26', '10');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6M4VOF1ExBRii1x20Pk0GR', 'Savage Remix (feat. Beyoncé)', '2020-04-29', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5emzM1P5GGeroiivNQgCq4', 'La Jeepeta (Remix)', '2020-04-24', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1MmVkhiwTH0BkNOU3nw5d3', 'Hot Pink', '2019-11-07', '12');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4g1ZRSobMefqF6nelkgibi', 'Hollywood_s Bleeding', '2019-09-06', '17');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3D1NZYi3GsenO5uWDFrRI6', '1 of 1', '2020-05-21', '21');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2wiPF3m0ylst0JSk1IvZL8', 'Divinely Uninspired To A Hellish Extent (Extended Edition)', '2019-11-22', '15');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5lJqux7orBlA1QzyiBGti1', 'YHLQMDLG', '2020-02-28', '20');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('42WVQWuf1teDysXiOupIZt', 'Birds In The Trap Sing McKnight', '2016-09-16', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5JpH5T1sCYnUyZD6TM0QaY', 'Cry Baby (Deluxe Edition)', '2015-08-14', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7AaqMMiYMvnMB3RcS8u3EY', 'Sweet Action', '2020-03-13', '7');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7JtT7OyWM8BnIS5FXXPMKg', 'Emmanuel', '2020-05-29', '22');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7tcs1X9pzFvcLOPuhCstQJ', 'Golden Hour', '2020-05-29', '18');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4KEOAWBMpvJrIZ7tQfx44i', 'TKN (feat. Travis Scott)', '2020-05-28', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1eleCBhP2R8TXEDquvybwC', 'Be Kind (with Halsey)', '2020-05-01', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3nR9B40hYLKLcR0Eph3Goc', 'Memories', '2019-09-20', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0xzScN8P3hQAz3BT3YYX5w', 'Shawn Mendes (Deluxe)', '2019-06-19', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2uDTi1PlpSpvAv7IRAoAEU', 'HIGHEST IN THE ROOM', '2019-10-04', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6HJDrXs0hpebaRFKA1sF90', 'ROXANNE', '2019-10-10', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('4bNPOFOzxGhF5jhfIK6lit', 'High Off Life', '2020-05-15', '21');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('42XA3CG4dOtlaVKq5ZRNRh', 'VACATION', '2020-06-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6ZTl8hHvYNuEg4Mk8yxz75', 'The Bigger Picture', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2PFiZ23ZyPTcgwmXk4X6o0', 'Tommy Lee (feat. Post Malone)', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('7z4GhRfLqfSkqrj5F3Yt2B', 'Heaven Or Hell', '2020-03-13', '12');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3EYg0XBIcyz3OvhIy7gsZQ', 'Walk Em Down (feat. Roddy Ricch)', '2020-03-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('40wtKuLVVlde1T88LqtZwa', 'GO (feat. Juice WRLD)', '2020-06-12', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3MJxH055n52Rbm8RLlpJcN', 'BLACK PARADE', '2020-06-19', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6uhEg4ASZYLIilZFCBFy1r', 'My Turn (Deluxe)', '2020-05-01', '26');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('39xhYyNNDatQtgKw2KdXMz', 'THE GOAT', '2020-05-15', '16');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('5hxLDyEJV1IvgoAquaImWW', 'Righteous', '2020-04-24', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('6tkjU4Umpo79wwkgPMV3nZ', 'Goodbye & Good Riddance', '2018-12-10', '17');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0gA0nZrZ55PLUp7ARfrICu', 'WUNNA', '2020-05-22', '18');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('37CqAwxTungNxKpIK5vSgE', 'hot girl bummer', '2019-08-23', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('2WrNHOba5u6P9S9xEboaUy', 'Perfect Ten', '2019-06-28', '10');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('3P7EIeXmzJQNT1xs4Q6Xzd', 'Sleepy Hallow Presents: Sleepy For President', '2020-06-05', '12');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1IR2nlwX6YVTXXeu2qzoWO', 'If I Know Me', '2018-04-27', '14');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('0MXpE6m0mEK0r3TuERb9Yd', 'Snow On Tha Bluff', '2020-06-16', '1');
INSERT INTO album ('album_id', 'name', 'release_date', 'total_track') VALUES ('1wEEKxybMlEo2Hob9oQA2y', 'Shotta Flow 5', '2020-06-12', '1');
