INSERT INTO artist ('artist_id', 'name') VALUES ('1aS5tqEs9ci5P9KD9tZWa6', 'Bonez MC');
INSERT INTO artist ('artist_id', 'name') VALUES ('4WZGDpNwrC0vNQyl9QzF7d', 'Capital Bra');
INSERT INTO artist ('artist_id', 'name') VALUES ('4WoSAKuoaPxrbwp3Y1PvKb', 'Bozza');
INSERT INTO artist ('artist_id', 'name') VALUES ('34LetYSjEuG2fBb4Z8PwPg', 'Pashanim');
INSERT INTO artist ('artist_id', 'name') VALUES ('4r63FhuTkUYltbVAg5TQnk', 'DaBaby');
INSERT INTO artist ('artist_id', 'name') VALUES ('757aE44tKEUQEqRuT6GnEB', 'Roddy Ricch');
INSERT INTO artist ('artist_id', 'name') VALUES ('5pVRwX5ZQR7hfJ18w8ZYkl', 'Ufo361');
INSERT INTO artist ('artist_id', 'name') VALUES ('5ZYOlPpI9FZu2uIPkTB0UA', 'CÉLINE');
INSERT INTO artist ('artist_id', 'name') VALUES ('1qQLhymHXFPtP5U8KNKsm6', 'Apache 207');
INSERT INTO artist ('artist_id', 'name') VALUES ('56mfhUDKa1vec6rSLZV5Eg', 'Jawsh 685');
INSERT INTO artist ('artist_id', 'name') VALUES ('07YZf4WDAMNwqr4jfgOZ8y', 'Jason Derulo');
INSERT INTO artist ('artist_id', 'name') VALUES ('07SFzTMeYf5P8Rd32a9Zzw', 'AK Ausserkontrolle');
INSERT INTO artist ('artist_id', 'name') VALUES ('5Yo5iU2nf4H41waPl4ZnS1', 'LEA');
INSERT INTO artist ('artist_id', 'name') VALUES ('1Xyo4u8uXC1ZmMpatF05PJ', 'The Weeknd');
INSERT INTO artist ('artist_id', 'name') VALUES ('09agIJMxCD2k87ys9Al0f0', 'VIZE');
INSERT INTO artist ('artist_id', 'name') VALUES ('6Rmg5JiRphFMlhkwGNl9Fu', 'Tom Gregory');
INSERT INTO artist ('artist_id', 'name') VALUES ('5sRQkVexJlax2iISuqL8cV', 'Kalazh44');
INSERT INTO artist ('artist_id', 'name') VALUES ('6h1s4i4XKIYv4ErDelLDN0', 'Samra');
INSERT INTO artist ('artist_id', 'name') VALUES ('1SnSPHBs8l5iAvoWF0aO05', 'FOURTY');
INSERT INTO artist ('artist_id', 'name') VALUES ('4sVieJlKgpZ2k9ESNS5IdN', 'Jamule');
INSERT INTO artist ('artist_id', 'name') VALUES ('0H39MdGGX6dbnnQPt6NQkZ', 'SAINt JHN');
INSERT INTO artist ('artist_id', 'name') VALUES ('5rGrDvrLOV2VV8SCFVGWlj', 'Imanbek');
INSERT INTO artist ('artist_id', 'name') VALUES ('5p7mWeX4RlvqBCxylfiXdE', 'KC Rebell');
INSERT INTO artist ('artist_id', 'name') VALUES ('3drqpTL4sQOckmAfF9i1wg', 'Summer Cem');
INSERT INTO artist ('artist_id', 'name') VALUES ('3CJKkU0XuElRT1z8rEtIYg', 'Luciano');
INSERT INTO artist ('artist_id', 'name') VALUES ('4npEfmQ6YuiwW1GpUmaq3F', 'Ava Max');
INSERT INTO artist ('artist_id', 'name') VALUES ('1lmU3giNF3CSbkVSQmLpHQ', 'Surf Mesa');
INSERT INTO artist ('artist_id', 'name') VALUES ('4ArPQ1Opcksbbf3CPwEjWE', 'Emilee');
INSERT INTO artist ('artist_id', 'name') VALUES ('0u6GtibW46tFX7koQ6uNJZ', 'Topic');
INSERT INTO artist ('artist_id', 'name') VALUES ('5Wg2b4Mp42gicxEeDNawf7', 'A7S');
INSERT INTO artist ('artist_id', 'name') VALUES ('4lDiJcOJ2GLCK6p9q5BgfK', 'Kontra K');
INSERT INTO artist ('artist_id', 'name') VALUES ('1yxSLGMDHlW21z4YXirZDS', 'Black Eyed Peas');
INSERT INTO artist ('artist_id', 'name') VALUES ('1i8SpTcr7yvPOmcqrbnVXY', 'Ozuna');
INSERT INTO artist ('artist_id', 'name') VALUES ('1OB278sOZVSFx5vXqYha83', 'J. Rey Soul');
INSERT INTO artist ('artist_id', 'name') VALUES ('2NJWI8byqTSqDaJRnqJY2z', 'KALIM');
INSERT INTO artist ('artist_id', 'name') VALUES ('18ISxWwWjV6rPLoVCXf1dz', 'RIN');
INSERT INTO artist ('artist_id', 'name') VALUES ('7qXzy6c5RWT0XlVQcOBIDG', 'Mark Forster');
INSERT INTO artist ('artist_id', 'name') VALUES ('60uPSVM3svOL8kZ3Wkb3Zw', 'Monet192');
INSERT INTO artist ('artist_id', 'name') VALUES ('3pjq2pDV9RR6VY55wBjVnp', 'Dardan');
INSERT INTO artist ('artist_id', 'name') VALUES ('3TVXtAsR1Inumwj472S9r4', 'Drake');
INSERT INTO artist ('artist_id', 'name') VALUES ('7oWrEQO1d3klp0Qrfh7a5h', 'badmómzjay');
INSERT INTO artist ('artist_id', 'name') VALUES ('7nqlScm2smydSRl13eaP8E', 'Nea');
INSERT INTO artist ('artist_id', 'name') VALUES ('4bL2B6hmLlMWnUEZnorEtG', 'Felix Jaehn');
INSERT INTO artist ('artist_id', 'name') VALUES ('2JwyRtuXf2l6sTnSnGVIa1', 'Farid Bang');
INSERT INTO artist ('artist_id', 'name') VALUES ('2jku7tDXc6XoB6MO2hFuqg', 'Tory Lanez');
INSERT INTO artist ('artist_id', 'name') VALUES ('2Z9KL8Zmqx5Sg3cd7Fldhl', 'Olexesh');
INSERT INTO artist ('artist_id', 'name') VALUES ('1ul8iLt2WnFe2UIyovjg7q', 'reezy');
INSERT INTO artist ('artist_id', 'name') VALUES ('13bDjug9N0pyv3ZUINjkDV', 'Bausa');
INSERT INTO artist ('artist_id', 'name') VALUES ('7gZfnEnfiaHzxARJ2LeXrf', '6ix9ine');
INSERT INTO artist ('artist_id', 'name') VALUES ('0hCNtLu0JehylgoiP8L4Gh', 'Nicki Minaj');
INSERT INTO artist ('artist_id', 'name') VALUES ('4hXT6A14n901v8DU5Of337', 'KAYEF');
INSERT INTO artist ('artist_id', 'name') VALUES ('2NjfBq1NflQcKSeiDooVjY', 'Tones And I');
INSERT INTO artist ('artist_id', 'name') VALUES ('03d2mJXSMtuPI0nIvLnhoS', 'Zoe Wees');
INSERT INTO artist ('artist_id', 'name') VALUES ('0Cp8WN4V8Tu4QJQwCN5Md4', 'BENEE');
INSERT INTO artist ('artist_id', 'name') VALUES ('6sHCvZe1PHrOAuYlwTLNH4', 'Gus Dapperton');
INSERT INTO artist ('artist_id', 'name') VALUES ('5ee4yhrWOxaxvL77BoVpVR', 'Lucky Luke');
INSERT INTO artist ('artist_id', 'name') VALUES ('4xcDVatLFh6qlcm41er3LV', 'Jerome');
INSERT INTO artist ('artist_id', 'name') VALUES ('1HY2Jd0NmPuamShAr6KMms', 'Lady Gaga');
INSERT INTO artist ('artist_id', 'name') VALUES ('66CXWjxzNUsdJxJ2JdwvnR', 'Ariana Grande');
INSERT INTO artist ('artist_id', 'name') VALUES ('3A9B6c1CrSPauiOblw7pWz', 'Nico Santos');
INSERT INTO artist ('artist_id', 'name') VALUES ('2Im8m4STDBosjfmb5hmP80', 'Loredana');
INSERT INTO artist ('artist_id', 'name') VALUES ('3t5xRXzsuZmMDkQzgOX35S', 'Robin Schulz');
INSERT INTO artist ('artist_id', 'name') VALUES ('3tXUeiWOSod3mSQ2lOautf', 'Wes');
INSERT INTO artist ('artist_id', 'name') VALUES ('1kiq2kUV0cbLUhJsr7cpW0', 'Alida');
INSERT INTO artist ('artist_id', 'name') VALUES ('6Mm2g25BTeJ6BICPFWGkPg', 'Bosh');
INSERT INTO artist ('artist_id', 'name') VALUES ('7DUTsWY3RBd64vh8UtgtYA', 'Lacrim');
INSERT INTO artist ('artist_id', 'name') VALUES ('0oeiA5U9u1U45Gos5cywUU', 'Soso Maness');
INSERT INTO artist ('artist_id', 'name') VALUES ('05hirnMeVIzCrcUxbrysZU', 'Hatik');
INSERT INTO artist ('artist_id', 'name') VALUES ('3IW7ScrzXmPvZhB27hmfgy', 'Jul');
INSERT INTO artist ('artist_id', 'name') VALUES ('1SxuyHZnLUFyFHGzdGaxZk', 'Wejdene');
INSERT INTO artist ('artist_id', 'name') VALUES ('4sbXXFzEWJY2zsZjelerjX', 'Dadju');
INSERT INTO artist ('artist_id', 'name') VALUES ('6Te49r3A6f5BiIgBRxH7FH', 'Ninho');
INSERT INTO artist ('artist_id', 'name') VALUES ('58wXmynHaAWI5hwlPZP3qL', 'Booba');
INSERT INTO artist ('artist_id', 'name') VALUES ('0mmk05vTtGGG2jYwLxRHwy', 'Zed');
INSERT INTO artist ('artist_id', 'name') VALUES ('3O5HD95HTEPgoPFOjAb7yV', 'DripReport');
INSERT INTO artist ('artist_id', 'name') VALUES ('0gGcw3tA1fZoF23qa8KFb7', 'Bolémvn');
INSERT INTO artist ('artist_id', 'name') VALUES ('6L34dW6SKMSDaGIfYDU19j', 'Maes');
INSERT INTO artist ('artist_id', 'name') VALUES ('1lB3I3SI30v2ZOpR4XQqzJ', 'Gambi');
INSERT INTO artist ('artist_id', 'name') VALUES ('6W5uA6CNMf3hd2j4a2XWCx', 'Naps');
INSERT INTO artist ('artist_id', 'name') VALUES ('0GgY7hjMoGDsX8ZDe2mwds', 'Soolking');
INSERT INTO artist ('artist_id', 'name') VALUES ('790FomKkXshlbRYZFtlgla', 'KAROL G');
INSERT INTO artist ('artist_id', 'name') VALUES ('54kCbQZaZWHnwwj9VP2hn4', 'Zola');
INSERT INTO artist ('artist_id', 'name') VALUES ('3xEJ7cDz5rdg6VM8E6Mqhf', 'DA Uzi');
INSERT INTO artist ('artist_id', 'name') VALUES ('5mmEMfYChd6MImBagU7zCs', 'Bigflo & Oli');
INSERT INTO artist ('artist_id', 'name') VALUES ('2EFpb61Lpi0l5ldOiqbZkK', 'Landy');
INSERT INTO artist ('artist_id', 'name') VALUES ('6bmlMHgSheBauioMgKv2tn', 'Powfu');
INSERT INTO artist ('artist_id', 'name') VALUES ('35l9BRT7MXmM8bv2WDQiyB', 'beabadoobee');
INSERT INTO artist ('artist_id', 'name') VALUES ('4ddqz1AzqYMRKYTslXO839', 'Doria');
INSERT INTO artist ('artist_id', 'name') VALUES ('6IYoNcihnYWgtCHRTLxk7H', 'Nessbeal');
INSERT INTO artist ('artist_id', 'name') VALUES ('6HCBnyTBSLdb3TFn2ayulY', 'Leto');
INSERT INTO artist ('artist_id', 'name') VALUES ('3DCWeG2J1fZeu0Oe6i5Q6m', 'PLK');
INSERT INTO artist ('artist_id', 'name') VALUES ('2LUi4eKMEFKFM4awgurcSs', '4Keus');
INSERT INTO artist ('artist_id', 'name') VALUES ('7CUFPNi1TU8RowpnFRSsZV', 'Niska');
INSERT INTO artist ('artist_id', 'name') VALUES ('2tcoLkA9Hexz70Kuc1NTUl', 'Gradur');
INSERT INTO artist ('artist_id', 'name') VALUES ('3YwqjMyrRfuixi2pbgTGCE', 'Heuss L_enfoiré');
INSERT INTO artist ('artist_id', 'name') VALUES ('6KImCVD70vtIoJWnq6nGn3', 'Harry Styles');
INSERT INTO artist ('artist_id', 'name') VALUES ('6M2wZ9GZgrQXHCFfjv46we', 'Dua Lipa');
INSERT INTO artist ('artist_id', 'name') VALUES ('1XLWox9w1Yvbodui0SRhUQ', 'StaySolidRocky');
INSERT INTO artist ('artist_id', 'name') VALUES ('5zctI4wO9XSKS8XwcnqEHk', 'Lil Mosey');
INSERT INTO artist ('artist_id', 'name') VALUES ('1uNFoZAHBGtllmzznpCI3s', 'Justin Bieber');
INSERT INTO artist ('artist_id', 'name') VALUES ('2PaZWGu5T5nHjY2xxAkFsT', 'THE SCOTTS');
INSERT INTO artist ('artist_id', 'name') VALUES ('0Y5tJX1MQlPlqiwlOH1tJY', 'Travis Scott');
INSERT INTO artist ('artist_id', 'name') VALUES ('0fA0VVWsXO9YnASrzqfmYu', 'Kid Cudi');
INSERT INTO artist ('artist_id', 'name') VALUES ('0VRj0yCOv2FXJNP47XQnx5', 'Quavo');
INSERT INTO artist ('artist_id', 'name') VALUES ('4GNC7GD6oZMSxPGyXy4MNB', 'Lewis Capaldi');
INSERT INTO artist ('artist_id', 'name') VALUES ('4ETSs924pXMzjIeD6E9b4u', 'Surfaces');
INSERT INTO artist ('artist_id', 'name') VALUES ('7uaIm6Pw7xplS8Dy06V6pT', 'Trevor Daniel');
INSERT INTO artist ('artist_id', 'name') VALUES ('181bsRPaVXVlUKXrxwZfHK', 'Megan Thee Stallion');
INSERT INTO artist ('artist_id', 'name') VALUES ('6vWDO969PvNqNYHIOW5v0m', 'Beyoncé');
INSERT INTO artist ('artist_id', 'name') VALUES ('5hdhHgpxyniooUiQVaPxQ0', 'Nio Garcia');
INSERT INTO artist ('artist_id', 'name') VALUES ('2R21vXR83lH98kGeO99Y66', 'Anuel AA');
INSERT INTO artist ('artist_id', 'name') VALUES ('7iK8PXO48WeuP03g8YR51W', 'Myke Towers');
INSERT INTO artist ('artist_id', 'name') VALUES ('1GKIlPFdcewHtpDVCQ8zmJ', 'Brray');
INSERT INTO artist ('artist_id', 'name') VALUES ('3Wb38LDP3N4tkobValgE9D', 'Juanka');
INSERT INTO artist ('artist_id', 'name') VALUES ('5cj0lLjcoR7YOSnhnX0Po5', 'Doja Cat');
INSERT INTO artist ('artist_id', 'name') VALUES ('246dkjvS1zLTtiykXe5h60', 'Post Malone');
INSERT INTO artist ('artist_id', 'name') VALUES ('77ziqFxp5gaInVrF2lj4ht', 'Sech');
INSERT INTO artist ('artist_id', 'name') VALUES ('4q3ewBCX7sLwd24euuV69X', 'Bad Bunny');
INSERT INTO artist ('artist_id', 'name') VALUES ('63yrD80RY3RNEM2YDpUpO8', 'Melanie Martinez');
INSERT INTO artist ('artist_id', 'name') VALUES ('2LIk90788K0zvyj2JJVwkJ', 'Jack Harlow');
INSERT INTO artist ('artist_id', 'name') VALUES ('4IMAo2UQchVFyPH24PAjUs', 'Jowell & Randy');
INSERT INTO artist ('artist_id', 'name') VALUES ('12vb80Km0Ew53ABfJOepVz', 'Nengo Flow');
INSERT INTO artist ('artist_id', 'name') VALUES ('23fqKkggKUBHNkbKtXEls4', 'Kygo');
INSERT INTO artist ('artist_id', 'name') VALUES ('5Pwc4xIPtQLFEnJriah9YJ', 'OneRepublic');
INSERT INTO artist ('artist_id', 'name') VALUES ('7ltDVBr6mKbRvohxheJ9h1', 'ROSALÍA');
INSERT INTO artist ('artist_id', 'name') VALUES ('64KEffDW9EtZ1y2vBYgq8T', 'Marshmello');
INSERT INTO artist ('artist_id', 'name') VALUES ('26VFTg2z8YR0cCuwLzESi2', 'Halsey');
INSERT INTO artist ('artist_id', 'name') VALUES ('04gDigrS5kc9YWfZHwBETP', 'Maroon 5');
INSERT INTO artist ('artist_id', 'name') VALUES ('7n2wHs1TKAczGzO7Dd2rGr', 'Shawn Mendes');
INSERT INTO artist ('artist_id', 'name') VALUES ('4nDoRrQiYLoBzwC5BhVJzF', 'Camila Cabello');
INSERT INTO artist ('artist_id', 'name') VALUES ('0vRvGUQVUjytro0xpb26bs', 'Arizona Zervas');
INSERT INTO artist ('artist_id', 'name') VALUES ('1RyvyyTE3xzB2ZywiAwp0i', 'Future');
INSERT INTO artist ('artist_id', 'name') VALUES ('5LHRHt1k9lMyONurDHEdrp', 'Tyga');
INSERT INTO artist ('artist_id', 'name') VALUES ('5f7VJjfbwm532GiveGC0ZK', 'Lil Baby');
INSERT INTO artist ('artist_id', 'name') VALUES ('1MXZ0hsGic96dWRDKwAwdr', 'Tyla Yaweh');
INSERT INTO artist ('artist_id', 'name') VALUES ('4Gso3d4CscCijv0lmajZWs', 'Don Toliver');
INSERT INTO artist ('artist_id', 'name') VALUES ('0ErzCpIMyLcjPiwT4elrtZ', 'NLE Choppa');
INSERT INTO artist ('artist_id', 'name') VALUES ('2tIP7SsRs7vjIcLrU85W8J', 'The Kid LAROI');
INSERT INTO artist ('artist_id', 'name') VALUES ('4MCBfE4596Uoi2O4DtmEMz', 'Juice WRLD');
INSERT INTO artist ('artist_id', 'name') VALUES ('1zNqQNIdeOUZHb8zbZRFMX', 'Swae Lee');
INSERT INTO artist ('artist_id', 'name') VALUES ('4fxd5Ee7UefO4CUXgwJ7IP', 'Giveon');
INSERT INTO artist ('artist_id', 'name') VALUES ('45gHcnDnMC15sgx3VL7ROG', '42 Dugg');
INSERT INTO artist ('artist_id', 'name') VALUES ('6AgTAQt8XS6jRWi4sX7w49', 'Polo G');
INSERT INTO artist ('artist_id', 'name') VALUES ('2hlmm7s2ICUX0LVIhVFlZQ', 'Gunna');
INSERT INTO artist ('artist_id', 'name') VALUES ('50co4Is1HCEo8bhOyUWKpn', 'Young Thug');
INSERT INTO artist ('artist_id', 'name') VALUES ('2cFrymmkijnjDg9SS92EPM', 'blackbear');
INSERT INTO artist ('artist_id', 'name') VALUES ('0YinUQ50QDB7ZxSCLyQ40k', 'Mustard');
INSERT INTO artist ('artist_id', 'name') VALUES ('6EPlBSH2RSiettczlz7ihV', 'Sleepy Hallow');
INSERT INTO artist ('artist_id', 'name') VALUES ('6trIghKwHRUyxwvm66HLHH', 'Fousheé');
INSERT INTO artist ('artist_id', 'name') VALUES ('4oUHIQIBe0LHzYfvXNW4QM', 'Morgan Wallen');
INSERT INTO artist ('artist_id', 'name') VALUES ('6l3HvQ5sa6mXTsMTB19rO5', 'J. Cole');
